apiVersion: apps/v1
kind: Deployment
metadata:
  name: makerculture-deployment
  labels:
    app: makerculture
spec:
  replicas: 1
  selector:
    matchLabels:
      app: makerculture
  template:
    metadata:
      labels:
        app: makerculture
    spec:
      securityContext:
        runAsUser: 1010420000
        fsGroup: 1010420000
      containers:
      - name: makerculture
        securityContext:
          runAsUser: 1010420000
        env:
        - name: GAB_TOKEN
          valueFrom:
            configMapKeyRef:
              name: makerculture-gab-token
              key: gab_token.txt
        - name: DISCORD_TOKEN
          valueFrom:
            configMapKeyRef:
              name: makerculture-discord-token
              key: discord_token.txt
        image: quay.io/dkirwan_redhat/makerculture:0.0.8
        imagePullPolicy: Always
        command: ["bundle"]
        restartPolicy: Always
        schedulerName: default-scheduler
        volumeMounts:
        - name: logs-pv-storage
          mountPath: /app/logs
        args: ["exec", "ruby", "/app/makerculture.rb", "$(DISCORD_TOKEN)", "$(GAB_TOKEN)"]
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 15
          periodSeconds: 60
      volumes:
      - name: logs-pv-storage
        persistentVolumeClaim:
          claimName: logs-pv-claim
