apiVersion: apps/v1
kind: Deployment
metadata:
  name: makerculture-deployment
  labels:
    app: makerculture
spec:
  replicas: 1
  selector:
    matchLabels:
      app: makerculture
  template:
    metadata:
      labels:
        app: makerculture
    spec:
      containers:
      - name: makerculture
        env:
        - name: DISCORD_TOKEN
          valueFrom:
            configMapKeyRef:
              name: makerculture-token
              key: discord_token.txt
        image: quay.io/dkirwan_redhat/makerculture:0.0.4
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        volumeMounts:
        - name: logs-pv-storage
          mountPath: /tmp/logs
        args: ["ruby /app/makerculture.rb $(DISCORD_TOKEN)"]
      volumes:
      - name: logs-pv-storage
        persistentVolumeClaim:
          claimName: logs-pv-claim
